### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by cjsb** [physhh/PCISPH#3]
Hello again,

I resolve the problem to run you code and now I can see the results =)

I saw the youtube videos and the results from the code are different from the youtube.
Do you have those new input files? And what technique did you used to get those amazing results?

Thank you for the attention

**Comment by ziish** [comment]
Hey again,
the files used in the videos should be the same as in the repository. In what way do your results differ?

**Comment by cjsb** [comment]
This is what I get from your code when I use the dambreak test case
![capture1](https://cloud.githubusercontent.com/assets/12685275/9484728/755317d0-4b86-11e5-8520-04d7519241f8.JPG)

Did I do something wrong?

**Comment by ziish** [comment]
Looks like the default particle size is used instead of the one specified for the scenes. The code for the scene loading is quite hacky. Just set a breakpoint to that [function](https://github.com/physhh/PCISPH/blob/master/PCISPH/src/scenes.cpp#L217) and check the `name` variable. It should match one in the if statemenets below where `particles_per_dimension` is customized per scene. The value of this variable defines how many subdivisions are done. So more subdivisisions => more particles.

Hope this helps.

**Comment by cjsb** [comment]
Great, thanks for the help!

I have a question, what method did you used to the boundary condition?

**Comment by ziish** [comment]
There is not too much special handling for the boundary. The boundary is made out of particles which are handled the same as the fluid particles, except that they are static.

**Comment by cjsb** [comment]
Do you have the name of the paper which explains the boundary solution?

**Comment by ziish** [comment]
There is no paper - As I said: The boundary particles are handled the same as the fluid particles but are static.
